### ISSUE TITLE
sample

### ISSUE THREAD

**Issue by piaohe20221128** [TeaPoly/CE-OptimizedLoss#1]
你好，感谢开源！问下在实际场景中beamsearch 和负采样在效果上有什么不同呢？各自适合的场景是什么呢？

**Comment by TeaPoly** [comment]
> 你好，感谢开源！问下在实际场景中beamsearch 和负采样在效果上有什么不同呢？各自适合的场景是什么呢？

I just implemented the algorithms of the two papers, and I mainly using MWER loss based on  beam search strategy for training. 
The final ASR performance with MWER loss based on  beam search strategy is better than negative sampling strategy. But negative sampling strategy is training faster than beam search strategy.

**Comment by piaohe20221128** [comment]
thankyou very much ！！
