### ISSUE TITLE
CTC MWER implementation

### ISSUE THREAD

**Issue by Ivan-Fan** [TeaPoly/CE-OptimizedLoss#3]
Really nice work! I noticed that this was for seq2seq. Do we have a CTC-based version of MWER in PyTorch? Or do you see any before? Thanks!

**Comment by TeaPoly** [comment]
> Really nice work! I noticed that this was for seq2seq. Do we have a CTC-based version of MWER in PyTorch? Or do you see any before? Thanks!

CTC based MWER based on PyTorch by @Mddct (I have not verified it):
https://github.com/Mddct/losses

**Comment by gswycf** [comment]
hi, can you wirte a ctc-based version  of mwer in pytorch. The CTC based MWER based on PyTorch by @Mddct involves c++, and it is not good to used. cmake shows a lot of errors

**Comment by TeaPoly** [comment]
Currently no plans for PyTorch MWER.  The core of MWER for CTC is beam search. You can read this link https://pytorch.org/audio/main/tutorials/asr_inference_with_ctc_decoder_tutorial.html
